from PySide6.QtWidgets import QPushButton

from bibleEdit import *


class Display_Content(BibleEdit):
    def __init__(self):
        super().__init__()
        #self.setupUi(self)

        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_1").clicked.connect(self.button_1)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_2").clicked.connect(self.button_2)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_3").clicked.connect(self.button_3)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_4").clicked.connect(self.button_4)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_5").clicked.connect(self.button_5)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_6").clicked.connect(self.button_6)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_7").clicked.connect(self.button_7)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_8").clicked.connect(self.button_8)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_9").clicked.connect(self.button_9)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_10").clicked.connect(self.button_10)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_11").clicked.connect(self.button_11)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_12").clicked.connect(self.button_12)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_13").clicked.connect(self.button_13)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_14").clicked.connect(self.button_14)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_15").clicked.connect(self.button_15)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_16").clicked.connect(self.button_16)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_17").clicked.connect(self.button_17)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_18").clicked.connect(self.button_18)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_19").clicked.connect(self.button_19)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_20").clicked.connect(self.button_20)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_21").clicked.connect(self.button_21)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_22").clicked.connect(self.button_22)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_23").clicked.connect(self.button_23)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_24").clicked.connect(self.button_24)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_25").clicked.connect(self.button_25)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_26").clicked.connect(self.button_26)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_27").clicked.connect(self.button_27)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_28").clicked.connect(self.button_28)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_29").clicked.connect(self.button_29)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_30").clicked.connect(self.button_30)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_31").clicked.connect(self.button_31)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_32").clicked.connect(self.button_32)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_33").clicked.connect(self.button_33)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_34").clicked.connect(self.button_34)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_35").clicked.connect(self.button_35)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_36").clicked.connect(self.button_36)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_37").clicked.connect(self.button_37)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_38").clicked.connect(self.button_38)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_39").clicked.connect(self.button_39)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_40").clicked.connect(self.button_40)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_41").clicked.connect(self.button_41)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_42").clicked.connect(self.button_42)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_43").clicked.connect(self.button_43)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_44").clicked.connect(self.button_44)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_45").clicked.connect(self.button_45)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_46").clicked.connect(self.button_46)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_47").clicked.connect(self.button_47)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_48").clicked.connect(self.button_48)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_49").clicked.connect(self.button_49)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_50").clicked.connect(self.button_50)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_51").clicked.connect(self.button_51)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_52").clicked.connect(self.button_52)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_53").clicked.connect(self.button_53)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_54").clicked.connect(self.button_54)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_55").clicked.connect(self.button_55)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_56").clicked.connect(self.button_56)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_57").clicked.connect(self.button_57)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_58").clicked.connect(self.button_58)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_59").clicked.connect(self.button_59)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_60").clicked.connect(self.button_60)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_61").clicked.connect(self.button_61)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_62").clicked.connect(self.button_62)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_63").clicked.connect(self.button_63)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_64").clicked.connect(self.button_64)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_65").clicked.connect(self.button_65)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_66").clicked.connect(self.button_66)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_67").clicked.connect(self.button_67)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_68").clicked.connect(self.button_68)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_69").clicked.connect(self.button_69)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_70").clicked.connect(self.button_70)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_71").clicked.connect(self.button_71)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_72").clicked.connect(self.button_72)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_73").clicked.connect(self.button_73)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_74").clicked.connect(self.button_74)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_75").clicked.connect(self.button_75)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_76").clicked.connect(self.button_76)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_77").clicked.connect(self.button_77)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_78").clicked.connect(self.button_78)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_79").clicked.connect(self.button_79)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_80").clicked.connect(self.button_80)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_81").clicked.connect(self.button_81)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_82").clicked.connect(self.button_82)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_83").clicked.connect(self.button_83)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_84").clicked.connect(self.button_84)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_85").clicked.connect(self.button_85)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_86").clicked.connect(self.button_86)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_87").clicked.connect(self.button_87)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_88").clicked.connect(self.button_88)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_89").clicked.connect(self.button_89)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_90").clicked.connect(self.button_90)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_91").clicked.connect(self.button_91)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_92").clicked.connect(self.button_92)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_93").clicked.connect(self.button_93)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_94").clicked.connect(self.button_94)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_95").clicked.connect(self.button_95)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_96").clicked.connect(self.button_96)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_97").clicked.connect(self.button_97)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_98").clicked.connect(self.button_98)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_99").clicked.connect(self.button_99)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_100").clicked.connect(self.button_100)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_101").clicked.connect(self.button_101)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_102").clicked.connect(self.button_102)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_103").clicked.connect(self.button_103)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_104").clicked.connect(self.button_104)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_105").clicked.connect(self.button_105)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_106").clicked.connect(self.button_106)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_107").clicked.connect(self.button_107)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_108").clicked.connect(self.button_108)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_109").clicked.connect(self.button_109)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_110").clicked.connect(self.button_110)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_111").clicked.connect(self.button_111)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_112").clicked.connect(self.button_112)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_113").clicked.connect(self.button_113)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_114").clicked.connect(self.button_114)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_115").clicked.connect(self.button_115)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_116").clicked.connect(self.button_116)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_117").clicked.connect(self.button_117)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_118").clicked.connect(self.button_118)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_119").clicked.connect(self.button_119)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_120").clicked.connect(self.button_120)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_121").clicked.connect(self.button_121)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_122").clicked.connect(self.button_122)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_123").clicked.connect(self.button_123)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_124").clicked.connect(self.button_124)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_125").clicked.connect(self.button_125)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_126").clicked.connect(self.button_126)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_127").clicked.connect(self.button_127)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_128").clicked.connect(self.button_128)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_129").clicked.connect(self.button_129)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_130").clicked.connect(self.button_130)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_131").clicked.connect(self.button_131)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_132").clicked.connect(self.button_132)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_133").clicked.connect(self.button_133)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_134").clicked.connect(self.button_134)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_135").clicked.connect(self.button_135)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_136").clicked.connect(self.button_136)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_137").clicked.connect(self.button_137)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_138").clicked.connect(self.button_138)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_139").clicked.connect(self.button_139)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_140").clicked.connect(self.button_140)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_141").clicked.connect(self.button_141)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_142").clicked.connect(self.button_142)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_143").clicked.connect(self.button_143)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_144").clicked.connect(self.button_144)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_145").clicked.connect(self.button_145)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_146").clicked.connect(self.button_146)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_147").clicked.connect(self.button_147)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_148").clicked.connect(self.button_148)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_149").clicked.connect(self.button_149)
        self.chaptersNumberInnerFrame.findChild(QPushButton, "chap_but_150").clicked.connect(self.button_150)

    def toggle_menu(self):
        if self.pushButton_menu.isChecked():
            self.leftScrollArea.hide()
        else:
            self.leftScrollArea.show()
        self.chaptersNumberFrame.hide()

    def toggle_content(self):
        if self.pushButton_content.isChecked():
            self.bibleBooksFrame.show()
        else:
            self.bibleBooksFrame.hide()
        self.stackedWidget.setCurrentIndex(0)
        self.chaptersNumberFrame.hide()

    def show_fun_facts_page(self):
        self.stackedWidget.setCurrentIndex(1)

    def show_study_plan(self):
        self.stackedWidget.setCurrentIndex(2)

    def show_study_topics(self):
        self.stackedWidget.setCurrentIndex(3)

    def show_study_character(self):
        self.stackedWidget.setCurrentIndex(4)

    def show_settings(self):
        self.stackedWidget.setCurrentIndex(5)